auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    enabled: true # Write-Ahead Log (WAL) for durability
  chunk_target_size: 1048576 # 1MB chunk size

frontend:
  forward_timeout: 10s
  compress_responses: true

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/cache
    resync_interval: 1m
  filesystem:
    directory: /data/loki/chunks

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
